services:
  proxy:
    image: rishi90containerregistery.azurecr.io/todoapi-singlenode-multicontainer-app-proxy
    ports:
      - "80:80"
    container_name: proxy
    networks:
      - TodoApi
  frontend:
    image: rishi90containerregistery.azurecr.io/todoapi-singlenode-multicontainer-app-frontend
    ports:
      - "80"
    depends_on:
      - backend
    container_name: frontend
    networks:
      - TodoApi
  backend:
    image: rishi90containerregistery.azurecr.io/todoapi-singlenode-multicontainer-app-backend
    ports:
      - "3000"
    container_name: backend
    networks:
      - TodoApi

networks:
  TodoApi: