services:
  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    ports:
      - "80:80"
    container_name: proxy
    networks:
      - TodoApi
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80"
    depends_on:
      - backend
    container_name: frontend
    networks:
      - TodoApi
  backend:
    build: 
      context: ./backend/TodoApi
      dockerfile: Dockerfile
    ports:
      - "3000"
    container_name: backend
    networks:
      - TodoApi
      
networks:
  TodoApi:
