version: '3'
services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend
    container_name: frontend
    networks:
      - TodoApi
  backend:
    build: 
      context: ./backend/TodoApi/TodoApi
      dockerfile: Dockerfile
    ports:
      - "8081:3000"
    container_name: backend
    networks:
      - TodoApi
networks:
  TodoApi:
